# Generated by Django 4.2.6 on 2024-04-27 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_document_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
